#!/bin/bash
# This script will clear your dns cache on your mac. It has been tested on macOS 13.4 Ventura
# Joshua Winters-Brown

if [ "$EUID" -ne 0 ]
    then echo "Please run this program as root, otherwise it will not work appropriately."
    exit
fi

dscacheutil -flushcache; killall -HUP mDNSResponder > /dev/null

echo "  _____ "
echo "  |   D "
echo "  |   | "
echo "  |   | "
echo "  \___|            _ "
echo "    ||  _______  -( (- "
echo "    |_'(-------)  '-' "
echo "       |       / "
echo " _____,-\__..__|_____ "
echo " "
echo " Your DNS has been flushed... "
