choco install googlechrome
choco install firefox
choco install jre8
choco install python3
choco install notepadplusplus.install
choco install 7zip.install
choco install zoom
choco install rustup.install
choco install steam
choco install bitwarden
choco install itunes
choco install putty
choco install nmap
choco install usbpcap
choco install wireshark
choco install powertoys
choco install github-desktop
choco install transmission
choco install visualstudio2022community
choco install googledrive
choco install filezilla
choco install sysinternals
choco install vlc
